### ISSUE TITLE
Help, the plugin is not starting issue.

### ISSUE THREAD

**Issue by ALBULAING** [jankiny/hexo-ai-abstract#1]
I am currently using a plugin, and although I have correctly configured the content, the plugin does not activate when I run `hexo g`. Additionally, the `aiabstact` field is not generated in the Front-Matter of my articles. Since the services of OpenAI are not accessible in my region, I am using a proxy API provided by another project. This proxy API works normally for other projects, so I am not clear why this plugin is not activated.
<img width="623" alt="wenti" src="https://github.com/user-attachments/assets/f46b5e13-5321-4750-984c-898687dc996a">

**Comment by jankiny** [comment]
enable设为on时，需要在博文的Front-Matter中增加`aiAbstract`（注意是`aiAbstract`而不是`aiabstact`）属性并空置。参考下图，插件会对Front-Matter中有`aiAbstract`属性并且其内容为空的博文生成AI摘要。

When enable is set to 'on', it is necessary to add the `aiAbstract` attribute (note that it is `aiAbstract`, not `aiabstact`) to the Front-Matter of the blog post and leave it empty. As shown in the image below, the plugin will generate AI abstract for blog posts that have the` aiAbstract` attribute with empty content in their Front-Matter.

![image](https://github.com/user-attachments/assets/86f02e14-a13f-40d1-b078-1d3bd16a1e4e)

具体参考[这里](https://github.com/jankiny/hexo-ai-abstract#1-test-your-_configyml)，enable设为on用于测试。测试完后，再将enable设为auto，会为所有的博文生成AI摘要。

> README.md#1-test-your-_configyml
> Specifically, when "enable" is set to "on," the AI summary generation _**will only be executed if the `aiAbstract` attribute of the post exists and is empty**_. Consequently, you can test the plugin's availability by adding the aiAbstract attribute to a post and leaving it empty.

**Comment by ALBULAING** [comment]
Okay, thank you very much.
